<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Ajax\Module'                        => __DIR__ . '/Module.php',
    'Ajax\Controller\AjaxController' => __DIR__ . '/src/Ajax/Controller/AjaxController.php',
    'Ajax\Model\AjaxModel' => __DIR__ . '/src/Ajax/Model/AjaxModel.php',
    'AjaxTest\Framework\TestCase'        => __DIR__ . '/tests/Ajax/Framework/TestCase.php',
    'AjaxTest\SampleTest'                => __DIR__ . '/tests/Ajax/SampleTest.php',
);
