<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module' => __DIR__ . '/Module.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Orm\Book\ApplicationBook' => __DIR__ . '/src/Application/Orm/Book/ApplicationBook.php',
    'Application\Orm\Book\Model\ApplicationBookDataTable' => __DIR__ . '/src/Application/Orm/Book/Model/ApplicationBookDataTable.php',
    'Application\Orm\Library\ApplicationLibrary' => __DIR__ . '/src/Application/Orm/Library/ApplicationLibrary.php',
    'Application\Orm\Library\Model\ApplicationLibraryDataTable' => __DIR__ . '/src/Application/Orm/Library/Model/ApplicationLibraryDataTable.php',
    'Application\Orm\ApplicationOrm' => __DIR__ . '/src/Application/Orm/ApplicationOrm.php',
);
