<?php
$this->layout()->face = $this->render('face/face');
$this->layout()->footer = $this->render('footer/footer');
?>
<?php echo $this->doctype(); ?>

<html lang="ru">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle('Стартовая страничка для продажи баннеров')?>

        <?php
        echo $this->headMeta()->
        // ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <!-- Le styles -->
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/cover.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
         ?>
        
        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ));
        ?>

    </head>
<body>
	<div class="site-wrapper">
		<div class="site-wrapper-inner">
			<div class="cover-container">
				<div class="masthead clearfix">
						<?php echo $this->face; ?>
					</div>
				<div class="inner cover">
						<?php echo $this->content; ?>
					</div>
				<div class="mastfoot clearfix">
						<?php echo $this->footer; ?>
					</div>
			</div>
		</div>
	</div>
        
		
        <?php echo $this->inlineScript()?>
    </body>
</html>
